### ISSUE TITLE
함수를 표시할 때 True/False 판단 중 크래시

### ISSUE THREAD

**Issue by tirr-c** [dragonteros/unsuspected-hangeul#5]
```
$ python pbhhg.py 'ㄱ ㄱ ㄷㅎㄷ ㅇㄱ ㅎ'
Traceback (most recent call last):
  File "pbhhg.py", line 336, in <module>
    print(main(sys.argv[1]))
  File "pbhhg.py", line 319, in main
    return str(to_printable(values[0]))
  File "pbhhg.py", line 297, in to_printable
    return decode_bool(value)
  File "pbhhg.py", line 185, in decode_bool
    if f == 0 and a.value == 0:
AttributeError: 'FunCall' object has no attribute 'value'
```

1. 레퍼런스 구현이 동적 인자 로드가 있는 함수를 표시할 때 에러가 납니다.
2. 이 경우는 ㅁ 연산자가 True로 판단하는 게 맞나요, 아니면 일반 함수로 판단하는 게 맞나요?

**Comment by dragonteros** [comment]
1. 고쳤습니다. 알려주셔서 감사합니다.
2. 조만간 bool 자료형을 별도로 지원하도록 할 예정입니다. 그 때는 `ㄱ ㅇㄱ ㅎ`도 일반함수로 취급하게 될 예정입니다.
